CREATE TABLE users (
	id UUID PRIMARY KEY,

	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(1024) UNIQUE NOT NULL,

	display_name VARCHAR(255) NOT NULL,
	username VARCHAR(255) UNIQUE NOT NULL,

	avatar_url VARCHAR(1024),
	banner_url VARCHAR(1024),

	role VARCHAR(64) NOT NULL DEFAULT 'regular',

	created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);